### ISSUE TITLE
Conduct a Qualitative Evaluation with Deaf Users

### ISSUE THREAD

**Issue by AmitMY** [sign-language-processing/spoken-to-signed-translation#1]
We need to evaluate the effectiveness of our text-to-gloss-to-pose-to-video generation system. To do this, we propose conducting a study to gather first impressions from deaf users. We've already recruited a group of deaf individuals who will use our system to translate text into sign language videos. They'll provide feedback on the system's accuracy, the quality of the poses and synthesized videos, and overall usability.

**Comment by radhavishnu** [comment]
Any Objective evaluation metrics has been carried out?

**Comment by AmitMY** [comment]
Yes. Across 5 different language pairs. the reports should be public in January
