### ISSUE TITLE
pose_to_video

### ISSUE THREAD

**Issue by GLWmax** [sign-language-processing/spoken-to-signed-translation#27]
PS C:\Users\Administrator\SignT\spoken-to-signed-translation> pose_& C:/Users/Administrator/AppData/Local/Programs/Python/Python311/python.exe c:/Users/Administrator/SignT/spoken-to-signed-translation/spoken_to_signed/pose_to_video/__init__.py
At line:1 char:6
+ pose_& C:/Users/Administrator/AppData/Local/Programs/Python/Python311 ...
+      ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass    
it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed

**Comment by AmitMY** [comment]
Seems like you are running a command `pose_&`. This is not a supported command
To perform pose-to-video, please advise: https://github.com/sign-language-processing/pose-to-video
