### ISSUE TITLE
related to the API

### ISSUE THREAD

**Issue by KhayitboevElbekjon** [sign-language-processing/spoken-to-signed-translation#30]
A text-to-glow-to-pose-to-video pipeline for SLP translation.
      Demos available:

Is there an API for this demo project?
![Screenshot from 2024-04-18 01-59-35](https://github.com/sign-language-processing/spoken-to-signed-translation/assets/123006944/3d09f892-5a88-4fcc-b42c-5bbd9c1fb00a)

**Comment by AmitMY** [comment]
There is no publically available, licensed API for this project.
There is only my implementation that is a hosting of this project by myself.

With the instructions in the README, you can download the swiss lexicon and expose it as an API if you want.

**Comment by KhayitboevElbekjon** [comment]
Hello, dearAmit MoryossefYes, that's understandable. Tell me, is it
possible to include the Uzbek language in the translation?

**Comment by AmitMY** [comment]
If you have a dataset for Uzbek, you can add it to be supported in this repository.
