### ISSUE TITLE
Release of gsg and bfi models?

### ISSUE THREAD

**Issue by Tortoise17** [sign-language-processing/spoken-to-signed-translation#33]
When will be gsg and bfi models expected to get released? If there is any information already?

**Comment by AmitMY** [comment]
To get `bfi` and `gsg` working, one needs to update the [`download_lexicon.py`](https://github.com/sign-language-processing/spoken-to-signed-translation/blob/main/spoken_to_signed/download_lexicon.py) file to support [`wordnet`](https://www.sign-lang.uni-hamburg.de/easier/sign-wordnet/).
There is a data loader one can use [here](https://github.com/sign-language-processing/datasets/tree/master/sign_language_datasets/datasets/sign_wordnet) but it might require some minor adjustments for the latest version of the wordnet.

I do not personally intend to add this to the repository, but if you wish, I will gladly review PRs.
(should not be more than 2-3 work hours)

**Comment by Tortoise17** [comment]
Just as quick question, is there any Spanish also available or multi-lingual model works for most of EU/Global languages ?

**Comment by AmitMY** [comment]
To get any language working with this repository, you just need a lexicon of the relevant language.
If you take a Spanish lexicon, it will work, etc. Wordnet has 8 languages.
