### ISSUE TITLE
Bug (and fix): Demo notebook: pose-to-video "command not found"

### ISSUE THREAD

**Issue by cleong110** [sign-language-processing/spoken-to-signed-translation#35]
I'd make a PR but I'm not sure the process with notebooks hosted on Drive. 

The [demo notebook ](https://colab.research.google.com/drive/1UtBmfBIhUa2EdLMnWJr0hxAOZelQ50_9) uses deprecated repo
```
! pip install git+https://github.com/sign-language-processing/transcription
```

Which results in `pose_to_video: command not found`

Which should be the updated repo
```
! pip install git+https://github.com/sign-language-processing/pose-to-video.git
```

Colab notebook demonstrating fix: https://colab.research.google.com/drive/1J505hIeLF2lcWXtRolaJatk2V2Zt8TYw?usp=sharing

**Comment by AmitMY** [comment]
done! thanks for catching this :)

**Comment by cleong110** [comment]
Yay! :)
