### ISSUE TITLE
Methodology for Translating English to ASL gloss

### ISSUE THREAD

**Issue by FrogInDizzy** [sign-language-processing/spoken-to-signed-translation#36]
I am currently engaged in a project aimed at translating English text into American Sign Language (ASL) gloss. I tried various methodologies, including deploying a local language model, I came across your innovative work with spaCy in rules.py and spacylemma.py. Your approach to linguistic transformations for German and French, especially in token manipulation and glossification, is quite impressive.

I was wondering do you think the methods you have developed could be adapted for English to ASL translation? Or perhaps you use different techniques for english to asl tranlation on sign.mt?

**Comment by AmitMY** [comment]
Personally, I think that "glosses" shouldn't be used except for quick proofs of concept (such as this repository).
If you want an English to ASL gloss translation, the spaCy based solution is viable - you can write the grammar rules for ASL, but I would recommend just using an LLM for that. In a few-shot scenario (give it a few sentences), it can also leverage a lot of info from the entire web to give you more accurate translations

**Comment by FrogInDizzy** [comment]
Thanks!
