### ISSUE TITLE
Easiest way to use this work on  python code ?

### ISSUE THREAD

**Issue by MendoLeo** [sign-language-processing/spoken-to-signed-translation#40]
There is a python library to use in easiest manner this work (text-to-pose model), by function calling a part command line provide on colab notebook to generate pose ?
I need to  know if it possible to just pip install "package" and use it in my python code for another project as sign-language movie subtitle(small project on which i'm working)?

**Comment by AmitMY** [comment]
From the README
```bash
pip install git+https://github.com/sign-language-processing/spoken-to-signed-translation.git
```
Then you can import whatever you want.

Here are example code, for all this library supports https://github.com/sign-language-processing/spoken-to-signed-translation/blob/main/spoken_to_signed/bin.py

**Comment by MendoLeo** [comment]
Thanks !
